version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


services:


### NGINX server ##############################################
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    networks:
        - frontend
        - backend
    command: [nginx-debug, '-g', 'daemon off;']

### PHP-FPM ##############################################

  php-fpm: 
    image: 'bitnami/php-fpm:7.2'
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./php-fpm/php.ini:/opt/bitnami/php/etc/php.ini
    links:
      - mysql
      - redis
    networks:
        - backend

### MYSQL server ##############################################

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - backend

### REDIS server ##############################################

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend